"""
pages/draft_intelligence.py
─────────────────────────────
Drop-in replacement for the Draft Analysis page in the fantasy football app.
Uses data/draft_vorp_full.csv and data/draft_vorp_summary.csv generated by
07_draft_analysis.py.

To integrate into app.py, replace the existing "Draft Analysis" tab section
with:

    from pages.draft_intelligence import render_draft_page
    with tab_draft:
        render_draft_page()

Or if the project uses st.sidebar navigation, add:
    "Draft Intelligence": render_draft_page

Data required (run 07_draft_analysis.py first):
    data/draft_vorp_full.csv
    data/draft_vorp_summary.csv
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from pathlib import Path

DATA = Path("data")

# ─────────────────────────────────────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────────────────────────────────────

YEAR_VERDICTS = {
    2021: {
        "theme": "Late QB Era Begins",
        "color": "#c8ff00",
        "winner": "RB R1–R3 + QB R7–R8",
        "avoid":  "WR rounds 6–9 (75–80% bust rate)",
        "surprise": "Stafford (R8 +8.22), Brady (R7 +4.74), Kupp (R4 +13.20)",
        "body": (
            "The late QB pattern emerges for the first time. Stafford (+8.22), "
            "Brady (+4.74), and Herbert (+4.58) were all available R6–R10 while "
            "premium picks on early QBs busted. Cooper Kupp's anomalous season "
            "(+13.20 VORP) was available at ADP 47 — a R4 pick that produced R1 "
            "results. RB R1–R3 was ironclad: Taylor, Ekeler, Mixon, Jacobs all hit."
        ),
    },
    2022: {
        "theme": "WR R1 Dominates — Early QB Exception",
        "color": "#ff4d6d",
        "winner": "WR R1–R2 + early QB (exception year)",
        "avoid":  "RB R5–R9",
        "surprise": "Breece Hall R4 (+6.98), Cordarrelle Patterson R8 (+4.37)",
        "body": (
            "The exception year — early QB actually paid off. Mahomes at R4 (+5.72) "
            "was QB1, and Allen/Goff/Cousins delivered across multiple slots. But late "
            "QBs also hit — Dak R7 (+2.94), Cousins R9 (+3.20), Goff R11 (+2.68). "
            "WR R1–R2 was the best positional window: Kupp, Adams, Diggs, Chase all "
            "posted 9+ VORP. Critical cautionary tale: Deebo Samuel bust at R2 (–2.06)."
        ),
    },
    2023: {
        "theme": "QB Bust Massacre",
        "color": "#00d4ff",
        "winner": "WR R1–R2 + late QB R7–R8",
        "avoid":  "QB rounds 3–5 (0% delivered meaningful VORP)",
        "surprise": "Kirk Cousins R8 was QB1 (+4.72). David Montgomery R6 (+6.79).",
        "body": (
            "The most validated year for late QB theory. Hurts, Lamar, Herbert, and "
            "Fields — all R3–R4 — all produced negative VORP. The best QB was Kirk "
            "Cousins at pick 90. WR R1–R2 was outstanding: Tyreek, ARSB, CeeDee, "
            "Jefferson all elite. The hidden gem: David Montgomery at R6 (+6.79) "
            "finished RB4 by VORP. TE was thin — Kelce alone at R1 delivered; "
            "streaming was valid."
        ),
    },
    2024: {
        "theme": "RB Market Corrects",
        "color": "#ffd700",
        "winner": "RB R1–R2 dominated. Joe Burrow R7.",
        "avoid":  "WR rounds 2–5 (mostly busts). Early QB beyond Allen/Lamar.",
        "surprise": "Brian Thomas Jr. R12 was WR2 (+8.07). Burrow R7 (+7.74).",
        "body": (
            "The market had been WR-leaning for two years. 2024 repriced RBs — Henry "
            "R2 (+10.06), Bijan R1 (+9.89), Gibbs R1 (+8.99), Saquon R1 (+8.73). "
            "Joe Burrow at R7 nearly won championships alone. Brian Thomas Jr. at pick "
            "142 is the single biggest late-round WR hit in the dataset. This year "
            "proves why static 'never draft RB R1' assumptions break down — the market "
            "had overcorrected and 2024 validated the correction."
        ),
    },
    2025: {
        "theme": "TE Market Explodes",
        "color": "#a855f7",
        "winner": "TE R4–R5 + RB R1–R2 + late QB R8–R10",
        "avoid":  "WR rounds 3–9 (historically bad bust rates)",
        "surprise": "McBride +10.14 VORP — dataset record. Javonte Williams R10 (+8.54).",
        "body": (
            "TE broke open for the first time. McBride's +10.14 VORP/gm is the highest "
            "per-game output of any non-QB in 5 years. Kittle at R5 (+8.56) and Tucker "
            "Kraft at R10 (+6.27) made TE the best positional value. Drake Maye at R10 "
            "was QB1 (+4.96) — Lamar at R2 busted (–1.60). The R9–R10 window produced "
            "Javonte Williams, Maye, and Kraft — the best late pocket in the dataset. "
            "WR R3–R9 had 62–71% bust rates, the worst in 5 years."
        ),
    },
}

BOARD_DATA = {
    2021: [
        ("R1",   None,  4.43,  4.46,  3.37, "Jonathan Taylor (RB +11.6)"),
        ("R2",   3.26,  2.24,  4.62,  1.76, "Justin Jefferson (WR +9.3)"),
        ("R3",   2.86,  2.69,  0.62,  0.68, "Josh Jacobs (RB +6.5)"),
        ("R4",   0.94,  0.27,  2.49,  None, "Cooper Kupp (WR +13.2)"),
        ("R5",   3.98,  1.98,  1.08,  2.73, "Dak Prescott (QB +4.0)"),
        ("R6",   3.14, -4.35, -1.73,  5.84, "Logan Thomas (TE +5.8)"),
        ("R7",   4.74, -3.24, -0.30, -0.76, "Tom Brady (QB +4.7)"),
        ("R8",   0.51,  1.82, -1.47, -1.38, "Matthew Stafford (QB +8.2)"),
        ("R9-10",-3.40,-2.97, -1.37,  0.48, "Joe Burrow (QB +3.5)"),
    ],
    2022: [
        ("R1",   None,  2.28,  9.18,  None, "Cooper Kupp (WR +11.5)"),
        ("R2",   2.74,  3.17,  3.11,  4.25, "Stefon Diggs (WR +9.8)"),
        ("R3",  -0.24,  1.72,  2.35,  None, "Ezekiel Elliott (RB +5.7)"),
        ("R4",   1.35,  2.04, -0.18, -0.40, "Breece Hall (RB +7.0)"),
        ("R5",  -0.48, -2.40,  0.92,  1.60, "DeAndre Hopkins (WR +3.8)"),
        ("R6",  -1.92, -1.18, -1.26,  0.00, "Tony Pollard (RB +1.5)"),
        ("R7",   1.37,  0.91, -0.86,  2.49, "Dallas Goedert (TE +3.3)"),
        ("R8",   0.06, -1.31, -1.50,  1.67, "C. Patterson (RB +4.4)"),
        ("R9-10",2.86, -1.92, -1.57,  0.28, "Tyler Lockett (WR +3.3)"),
    ],
    2023: [
        ("R1",   None,  3.42,  3.93,  3.05, "Tyreek Hill (WR +11.6)"),
        ("R2",   2.48,  0.51,  4.16,  None, "Amon-Ra St. Brown (WR +11.0)"),
        ("R3",  -1.33, -0.01,  0.48,  1.19, "Amari Cooper (WR +3.4)"),
        ("R4",  -1.43, -1.58,  0.58,  None, "Keenan Allen (WR +2.9)"),
        ("R5",  -1.54, -0.74, -0.65,  2.42, "T.J. Hockenson (TE +2.5)"),
        ("R6",  -3.20,  1.28,  0.57,  0.12, "Mike Evans (WR +7.1)"),
        ("R7",   0.82,  None, -3.17,  0.00, "Dak Prescott (QB +3.0)"),
        ("R8",  -3.00, -4.07, -1.61,  None, "Courtland Sutton (WR +5.3)"),
        ("R9-10",-2.52,-1.27, -3.48,  0.26, "Raheem Mostert (RB +6.6)"),
    ],
    2024: [
        ("R1",   None,  5.81,  4.30,  None, "Bijan Robinson (RB +9.9)"),
        ("R2",   None,  4.65, -0.35,  None, "Derrick Henry (RB +10.1)"),
        ("R3",  -0.39,  3.01,  0.09,  1.92, "Joe Mixon (RB +8.4)"),
        ("R4",   0.52,  2.30,  0.69,  None, "DeVonta Smith (WR +6.7)"),
        ("R5",   0.18,  0.62, -1.28,  5.21, "Mark Andrews (TE +5.9)"),
        ("R6",  -1.42, -3.28,  2.01, -0.14, "Chris Godwin Jr. (WR +6.7)"),
        ("R7",   4.80, -1.01, -3.32,  None, "Joe Burrow (QB +7.7)"),
        ("R8",   1.18, -2.46, -1.59, -0.38, "Jared Goff (QB +4.1)"),
        ("R9-10",-1.49,-3.53, -3.80,  1.03, "Brock Bowers (TE +3.4)"),
    ],
    2025: [
        ("R1",   None,  3.44,  2.61,  None, "Derrick Henry (RB +9.2)"),
        ("R2",  -1.60,  2.93,  2.94,  None, "Puka Nacua (WR +8.3)"),
        ("R3",   0.67,  0.85,  0.94,  0.82, "Davante Adams (WR +6.6)"),
        ("R4",   None,  0.13,  2.07, 10.14, "Trey McBride (TE +10.1)"),
        ("R5",  -0.27, -0.80, -0.28,  8.56, "George Kittle (TE +8.6)"),
        ("R6",  -1.28, -2.97, -1.35,  0.80, "George Pickens (WR +3.1)"),
        ("R7",   None,  0.08, -0.14,  0.66, "Jauan Jennings (WR +4.3)"),
        ("R8",   2.53, -0.03, -3.14,  None, "Dak Prescott (QB +4.8)"),
        ("R9-10", 0.16, 3.10, -3.59,  1.59, "Javonte Williams (RB +8.5)"),
    ],
}

LATE_HITS = {
    2021: [("Matthew Stafford","QB",85.2,8,8.22),("Ja'Marr Chase","WR",77.3,7,6.76),
           ("James Conner","RB",87.5,8,5.52),("Tom Brady","QB",76.4,7,4.74),("Joe Burrow","QB",110.2,10,3.50)],
    2022: [("Cordarrelle Patterson","RB",90.6,8,4.37),("Tyler Lockett","WR",106.5,9,3.32),
           ("Dallas Goedert","TE",77.8,7,3.26),("Kirk Cousins","QB",107.4,9,3.20),("Dak Prescott","QB",79.2,7,2.94)],
    2023: [("Raheem Mostert","RB",110.2,10,6.59),("Courtland Sutton","WR",92.9,8,5.26),
           ("Kirk Cousins","QB",90.6,8,4.72),("Gus Edwards","RB",141.3,12,4.48),("Jared Goff","QB",120.7,11,3.00)],
    2024: [("Brian Thomas Jr.","WR",142.9,12,8.07),("Chuba Hubbard","RB",121.3,11,7.89),
           ("Joe Burrow","QB",81.0,7,7.74),("J.K. Dobbins","RB",120.3,11,5.98),("Jared Goff","QB",92.3,8,4.10)],
    2025: [("Javonte Williams","RB",112.8,10,8.54),("Tucker Kraft","TE",108.5,10,6.27),
           ("Drake Maye","QB",116.1,10,4.96),("Dak Prescott","QB",85.3,8,4.80),("Dallas Goedert","TE",133.6,12,4.70)],
}

EARLY_BUSTS = {
    2021: [("Julio Jones","WR",44.3,4,-3.35)],
    2022: [("Lamar Jackson","QB",47.3,4,-3.02),("DJ Moore","WR",40.8,4,-2.42),
           ("D'Andre Swift","RB",10.8,1,-2.29),("Deebo Samuel Sr.","WR",21.3,2,-2.06)],
    2023: [("Jalen Hurts","QB",25.7,3,-3.56),("Justin Fields","QB",47.7,4,-3.40),
           ("Lamar Jackson","QB",35.9,3,-2.92),("Justin Herbert","QB",44.9,4,-2.68),("Miles Sanders","RB",45.9,4,-3.56)],
    2024: [("Deebo Samuel Sr.","WR",18.2,2,-5.41),("Brandon Aiyuk","WR",40.5,4,-3.31),
           ("Jaylen Waddle","WR",30.9,3,-3.21),("Jalen Hurts","QB",33.9,3,-3.02),("Chris Olave","WR",25.3,3,-2.91)],
    2025: [("Xavier Worthy","WR",46.5,4,-2.55),("Chuba Hubbard","RB",35.1,3,-2.51),
           ("Alvin Kamara","RB",36.9,4,-2.31)],
}

PERSISTENT_GAPS = [
    ("RB","R1",  3.88,"undervalued",5,[4.43,2.28,3.42,5.81,3.44],"Best consistent round in fantasy — 5/5 years positive"),
    ("WR","R1",  4.89,"undervalued",5,[4.46,9.18,3.93,4.30,2.61],"Only round WR matches RB reliability"),
    ("RB","R2",  3.17,"undervalued",5,[2.24,3.17,2.87,4.65,2.93],"Most reliable non-R1 pick in the dataset"),
    ("WR","R2",  3.18,"undervalued",5,[4.62,4.53,4.16,-0.34,2.94],"Strong floor — 2024 exception when WR market collapsed"),
    ("QB","R7",  2.33,"undervalued",3,[4.74,1.37,0.82,4.80,None],"Prescott/Burrow/Brady hit here repeatedly"),
    ("TE","R5",  3.45,"undervalued",3,[2.72,None,2.42,5.22,8.56],"Kelce/Kittle/Andrews tier — highest value pick in draft"),
    ("WR","R8", -1.94,"overpaid",   5,[-1.87,-1.50,-1.61,-1.59,-3.14],"Worst consistent round — never positive"),
    ("WR","R10",-4.05,"overpaid",   5,[-2.14,-3.29,-4.58,-6.34,-3.92],"Complete wasteland — 5/5 years negative"),
    ("RB","R9", -2.81,"overpaid",   5,[-2.71,-2.48,-3.73,-5.50,0.38],"Nearly never works — avoid"),
    ("RB","R6", -1.48,"overpaid",   4,[None,-0.95,1.28,-3.28,-2.97],"Handcuff trap round"),
]

POS_COLORS = {"QB": "#c8ff00", "RB": "#00d4ff", "WR": "#ff4d6d", "TE": "#ffd700"}

# ─────────────────────────────────────────────────────────────────────────────
# DATA LOADERS
# ─────────────────────────────────────────────────────────────────────────────

@st.cache_data
def load_full():
    path = DATA / "draft_vorp_full.csv"
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


@st.cache_data
def load_summary():
    path = DATA / "draft_vorp_summary.csv"
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


# ─────────────────────────────────────────────────────────────────────────────
# CHART HELPERS
# ─────────────────────────────────────────────────────────────────────────────

PLOTLY_THEME = dict(
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)",
    font=dict(family="Space Mono, monospace", color="#e8e8f0", size=11),
    margin=dict(l=10, r=10, t=40, b=10),
    xaxis=dict(gridcolor="#1e1e2e", showline=False, zeroline=False),
    yaxis=dict(gridcolor="#1e1e2e", showline=False, zeroline=False),
)


def vorp_color(v):
    if v is None:       return "#1a1a2a"
    if v >= 5:          return "rgba(200,255,0,0.85)"
    if v >= 3:          return "rgba(200,255,0,0.55)"
    if v >= 1:          return "rgba(200,255,0,0.30)"
    if v >= 0:          return "rgba(200,255,0,0.10)"
    if v >= -2:         return "rgba(255,77,109,0.30)"
    return "rgba(255,77,109,0.65)"


def render_board_chart(year):
    rows = BOARD_DATA[year]
    labels = [r[0] for r in rows]
    positions = ["QB", "RB", "WR", "TE"]

    fig = go.Figure()

    for i, pos in enumerate(positions):
        vals = [r[i + 1] for r in rows]
        colors = [vorp_color(v) for v in vals]
        text   = [f"{v:+.1f}" if v is not None else "—" for v in vals]
        fig.add_trace(go.Bar(
            name=pos,
            x=labels,
            y=[abs(v) if v is not None else 0 for v in vals],
            text=text,
            textposition="inside",
            marker_color=colors,
            marker_line_width=0,
            width=0.18,
            offset=(i - 1.5) * 0.19,
            showlegend=True,
            legendgroup=pos,
        ))

    fig.update_layout(
        **PLOTLY_THEME,
        barmode="overlay",
        height=320,
        title=dict(text=f"{year} — VORP/gm by Pick Range & Position", font_size=13),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, x=0),
        xaxis_title=None,
        yaxis_title="VORP/gm (abs)",
    )
    return fig


def render_vorp_heatmap(df_summary, year=None):
    """Heatmap of avg VORP/gm: rows = rounds, cols = positions."""
    data = df_summary if year is None else df_summary[df_summary["season"] == year]
    pivot = data.pivot_table(index="adp_round", columns="position",
                              values="avg_vorp_pg", aggfunc="mean")
    pivot = pivot.reindex(columns=["QB","RB","WR","TE"])
    pivot = pivot[pivot.index <= 13]

    fig = go.Figure(data=go.Heatmap(
        z=pivot.values,
        x=["QB","RB","WR","TE"],
        y=[f"R{r}" for r in pivot.index],
        colorscale=[[0,"#ff4d6d"],[0.4,"#1e1e2e"],[1,"#c8ff00"]],
        zmid=0,
        text=[[f"{v:+.2f}" if not np.isnan(v) else "—" for v in row] for row in pivot.values],
        texttemplate="%{text}",
        textfont=dict(size=11, family="Space Mono"),
        showscale=True,
        colorbar=dict(title="VORP/gm", tickfont=dict(size=9)),
    ))
    title_str = f"{year} VORP/gm Heatmap" if year else "5-Year Avg VORP/gm Heatmap"
    fig.update_layout(**PLOTLY_THEME, height=380, title=dict(text=title_str, font_size=13))
    return fig


def render_player_scatter(df_full, year):
    s = df_full[df_full["season"] == year].copy()
    color_map = {"Elite":"#c8ff00","Hit":"#00ff88","Contributor":"#888888",
                 "Neutral":"#555577","Bust":"#ff8888","Disaster":"#ff4d6d"}
    fig = px.scatter(
        s, x="adp", y="vorp_pg", color="outcome", symbol="position",
        hover_name="player_name",
        hover_data={"adp":":.1f","vorp_pg":":.2f","position":True,"outcome":True},
        color_discrete_map=color_map,
        labels={"adp":"Draft ADP","vorp_pg":"VORP per game"},
        title=f"{year} — Every Drafted Player: ADP vs Actual VORP/gm",
        height=420,
    )
    fig.add_hline(y=0, line_dash="dash", line_color="#444", line_width=1)
    fig.update_traces(marker=dict(size=8, line=dict(width=0)))
    fig.update_layout(**PLOTLY_THEME)
    return fig


# ─────────────────────────────────────────────────────────────────────────────
# COMPONENT RENDERS
# ─────────────────────────────────────────────────────────────────────────────

def _badge(pos):
    colors = {"QB":("#c8ff00","#0a200a"),"RB":("#00d4ff","#001a20"),
              "WR":("#ff4d6d","#200010"),"TE":("#ffd700","#201500")}
    bg, fg = colors.get(pos, ("#888","#000"))
    return f'<span style="background:{bg};color:{fg};padding:2px 7px;border-radius:2px;font-size:10px;font-weight:700;letter-spacing:0.1em">{pos}</span>'


def _vorp_chip(v):
    c = "#00ff88" if v >= 1 else "#888" if v >= 0 else "#ff4d6d"
    return f'<span style="color:{c};font-weight:700;font-family:Space Mono">{v:+.2f}</span>'


def render_verdict(year):
    d = YEAR_VERDICTS[year]
    col_color = d["color"]
    st.markdown(f"""
    <div style="border:1px solid {col_color};background:rgba(255,255,255,0.02);
                padding:20px 24px;border-radius:2px;margin-bottom:16px">
      <div style="font-size:10px;letter-spacing:0.3em;color:{col_color};
                  text-transform:uppercase;margin-bottom:8px;font-family:Space Mono">
        {year} · {d['theme']}
      </div>
      <div style="font-size:13px;line-height:1.7;color:#e8e8f0;margin-bottom:12px">
        {d['body']}
      </div>
      <div style="display:flex;gap:32px;margin-top:8px">
        <div>
          <div style="font-size:9px;letter-spacing:0.2em;color:#666;margin-bottom:3px">WIN WITH</div>
          <div style="font-size:12px;color:#00ff88">{d['winner']}</div>
        </div>
        <div>
          <div style="font-size:9px;letter-spacing:0.2em;color:#666;margin-bottom:3px">AVOID</div>
          <div style="font-size:12px;color:#ff4d6d">{d['avoid']}</div>
        </div>
        <div>
          <div style="font-size:9px;letter-spacing:0.2em;color:#666;margin-bottom:3px">SURPRISE</div>
          <div style="font-size:12px;color:#ffd700">{d['surprise']}</div>
        </div>
      </div>
    </div>
    """, unsafe_allow_html=True)


def render_player_table(players, is_hit):
    rows_html = ""
    for name, pos, adp, rnd, vorp in players:
        color = "#00ff88" if is_hit else "#ff4d6d"
        sign  = "+" if vorp > 0 else ""
        rows_html += f"""
        <div style="display:flex;align-items:center;padding:10px 12px;
                    border-bottom:1px solid #1e1e2e;gap:12px">
          <div style="min-width:28px;font-size:16px;font-weight:800;
                      color:#1e1e2e;font-family:Syne,sans-serif">
            {players.index((name,pos,adp,rnd,vorp))+1}
          </div>
          <div style="flex:1">
            <div style="font-weight:700;font-size:13px">{name}</div>
            <div style="font-size:10px;color:#6b6b85">ADP {adp:.1f} · Round {rnd}</div>
          </div>
          {_badge(pos)}
          <div style="font-family:Space Mono;font-size:15px;font-weight:700;color:{color}">
            {sign}{vorp:.2f}
          </div>
        </div>"""
    st.markdown(f'<div style="border:1px solid #1e1e2e;background:#111118">{rows_html}</div>',
                unsafe_allow_html=True)


def render_persistent_gaps():
    st.markdown("""
    <div style="font-size:9px;letter-spacing:0.4em;color:#c8ff00;
                text-transform:uppercase;margin-bottom:12px">
      Persistent Market Inefficiencies — Same Holes Every Year
    </div>
    """, unsafe_allow_html=True)

    header = """
    <div style="display:grid;grid-template-columns:60px 60px 90px 130px 80px 160px 1fr;
                gap:8px;padding:8px 12px;background:#0a0a0f;
                font-size:9px;letter-spacing:0.2em;color:#555;border-bottom:1px solid #1e1e2e">
      <div>POS</div><div>RND</div><div>VORP/GM</div><div>SIGNAL</div>
      <div>SEASONS</div><div>YEAR TREND</div><div>NOTE</div>
    </div>"""

    rows_html = ""
    for pos, rnd, avg, direction, seasons, yearly, note in sorted(
            PERSISTENT_GAPS, key=lambda x: abs(x[2]), reverse=True):
        color     = "#00ff88" if direction == "undervalued" else "#ff4d6d"
        label     = "↑ UNDERVALUED" if direction == "undervalued" else "↓ OVERPAID"
        vorp_str  = f"{avg:+.2f}"
        pos_color = POS_COLORS.get(pos, "#888")

        dots = ""
        for i, v in enumerate(yearly):
            yr = [21,22,23,24,25][i]
            if v is None:
                dots += f'<span style="display:inline-flex;align-items:center;justify-content:center;width:22px;height:22px;background:#1a1a2a;color:#333;font-size:8px;border-radius:2px;margin:1px">\'  {yr}</span>'
            else:
                bg = "rgba(0,255,136,0.3)" if v > 0 else "rgba(255,77,109,0.3)"
                tc = "#00ff88" if v > 0 else "#ff4d6d"
                dots += f'<span style="display:inline-flex;align-items:center;justify-content:center;width:22px;height:22px;background:{bg};color:{tc};font-size:8px;border-radius:2px;margin:1px;font-weight:700" title="{[2021,2022,2023,2024,2025][i]}: {v:+.1f}">{yr}</span>'

        rows_html += f"""
        <div style="display:grid;grid-template-columns:60px 60px 90px 130px 80px 160px 1fr;
                    gap:8px;padding:9px 12px;border-bottom:1px solid rgba(255,255,255,0.04);
                    align-items:center">
          <div><span style="background:{pos_color}20;color:{pos_color};padding:2px 7px;
               font-size:9px;font-weight:700;border-radius:2px">{pos}</span></div>
          <div style="color:#888;font-size:11px">{rnd}</div>
          <div style="font-family:Space Mono;font-size:14px;font-weight:700;color:{color}">{vorp_str}</div>
          <div style="color:{color};font-size:11px">{label}</div>
          <div style="color:#888;font-size:10px">{seasons}/5 yrs</div>
          <div style="display:flex">{dots}</div>
          <div style="font-size:10px;color:#6b6b85">{note}</div>
        </div>"""

    st.markdown(f'<div style="border:1px solid #1e1e2e;background:#111118">{header}{rows_html}</div>',
                unsafe_allow_html=True)


# ─────────────────────────────────────────────────────────────────────────────
# MAIN RENDER FUNCTION
# ─────────────────────────────────────────────────────────────────────────────

def render_draft_page():
    st.markdown("""
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Syne:wght@400;700;800&display=swap');
      .draft-header { font-family: Syne, sans-serif; font-size: 36px;
                      font-weight: 800; letter-spacing: -0.02em; margin-bottom: 4px; }
      .draft-sub    { font-family: Space Mono, monospace; font-size: 11px;
                      color: #6b6b85; letter-spacing: 0.15em; margin-bottom: 24px; }
      section-lbl   { font-size: 9px; letter-spacing: 0.4em; color: #c8ff00;
                      text-transform: uppercase; }
    </style>
    """, unsafe_allow_html=True)

    st.markdown('<div class="draft-header">Draft <span style="color:#c8ff00">Intelligence</span></div>', unsafe_allow_html=True)
    st.markdown('<div class="draft-sub">HALF PPR · 12-TEAM · 2021–2025 · VORP/GAME ANALYSIS</div>', unsafe_allow_html=True)

    full_df    = load_full()
    summary_df = load_summary()

    if full_df.empty:
        st.warning("Run `py 07_draft_analysis.py` first to generate `data/draft_vorp_full.csv`.")
        return

    # ── Tab navigation ──────────────────────────────────────────────────────
    tab_names = ["2021","2022","2023","2024","2025","↗ Trends"]
    tabs = st.tabs(tab_names)

    for i, (tab, year) in enumerate(zip(tabs[:5], [2021,2022,2023,2024,2025])):
        with tab:
            d = YEAR_VERDICTS[year]

            # Top KPIs
            c1, c2, c3, c4 = st.columns(4)
            top_players = {}
            for pos in ["QB","RB","WR","TE"]:
                pdf = full_df[(full_df["season"]==year) & (full_df["position"]==pos)]
                if not pdf.empty:
                    top_players[pos] = pdf.nlargest(1,"vorp_pg").iloc[0]

            for col, pos in zip([c1,c2,c3,c4], ["QB","RB","WR","TE"]):
                with col:
                    if pos in top_players:
                        p = top_players[pos]
                        pcolor = POS_COLORS[pos]
                        st.markdown(f"""
                        <div style="border:1px solid #1e1e2e;background:#111118;padding:16px;
                                    border-top:3px solid {pcolor}">
                          <div style="font-size:9px;letter-spacing:0.2em;color:#666;margin-bottom:6px">
                            {pos}1 · BEST VALUE
                          </div>
                          <div style="font-family:Syne,sans-serif;font-size:15px;font-weight:700">
                            {p['player_name']}
                          </div>
                          <div style="font-size:11px;color:{pcolor};margin-top:4px">
                            {p['vorp_pg']:+.2f} VORP/gm · {p['fpts_pg']:.1f} pts/gm
                          </div>
                          <div style="font-size:10px;color:#555;margin-top:2px">
                            ADP {p['adp']:.1f} · Round {int(p['adp_round'])}
                          </div>
                        </div>
                        """, unsafe_allow_html=True)

            st.markdown("<br>", unsafe_allow_html=True)
            render_verdict(year)

            # Board heatmap + scatter
            col_a, col_b = st.columns([1.1, 1])
            with col_a:
                st.plotly_chart(render_board_chart(year), use_container_width=True)
            with col_b:
                st.plotly_chart(render_vorp_heatmap(summary_df, year), use_container_width=True)

            # Scatter
            st.plotly_chart(render_player_scatter(full_df, year), use_container_width=True)

            # Late hits / early busts
            col_l, col_r = st.columns(2)
            with col_l:
                st.markdown("**Late Hits** — R7+, VORP > +3.0")
                render_player_table(LATE_HITS[year], is_hit=True)
            with col_r:
                st.markdown("**Early Busts** — R1–4, VORP < –2.0")
                render_player_table(EARLY_BUSTS[year], is_hit=False)

    # ── TRENDS TAB ──────────────────────────────────────────────────────────
    with tabs[5]:
        st.markdown("""
        <div style="border:1px solid #00d4ff;background:rgba(0,212,255,0.03);
                    padding:20px 24px;margin-bottom:24px">
          <div style="font-size:10px;letter-spacing:0.3em;color:#00d4ff;margin-bottom:8px">
            THE CORE FINDING
          </div>
          <div style="font-size:13px;line-height:1.7">
            Carrying strategic assumptions year-to-year is the wrong model.
            <strong style="color:#c8ff00">Each year has a unique ADP structure that creates different holes.</strong>
            The consistent signal isn't "always do X" — it's "find where the market mispriced
            players relative to their actual output." The persistent gaps below are where the
            market has been systematically wrong for 5 straight years. Everything else should
            be evaluated fresh from the current ADP board.
          </div>
        </div>
        """, unsafe_allow_html=True)

        # 5-year heatmap
        st.plotly_chart(render_vorp_heatmap(summary_df, year=None), use_container_width=True)

        render_persistent_gaps()

        st.markdown("<br>", unsafe_allow_html=True)
        st.markdown("##### Year-by-Year Character Summary")

        cols = st.columns(5)
        for col, year in zip(cols, [2021,2022,2023,2024,2025]):
            d = YEAR_VERDICTS[year]
            with col:
                st.markdown(f"""
                <div style="border:1px solid #1e1e2e;padding:14px;
                            border-top:3px solid {d['color']};background:#111118">
                  <div style="font-family:Syne,sans-serif;font-size:24px;font-weight:800;
                              color:{d['color']}">{year}</div>
                  <div style="font-size:11px;font-weight:700;margin:6px 0 10px">{d['theme']}</div>
                  <div style="font-size:9px;color:#555;letter-spacing:0.15em;margin-bottom:3px">WIN</div>
                  <div style="font-size:10px;color:#00ff88;margin-bottom:8px">{d['winner']}</div>
                  <div style="font-size:9px;color:#555;letter-spacing:0.15em;margin-bottom:3px">AVOID</div>
                  <div style="font-size:10px;color:#ff4d6d">{d['avoid']}</div>
                </div>
                """, unsafe_allow_html=True)

        st.markdown("<br>", unsafe_allow_html=True)
        st.markdown("""
        <div style="border:1px solid #ffd700;background:rgba(255,215,0,0.03);
                    padding:20px 24px">
          <div style="font-size:10px;letter-spacing:0.3em;color:#ffd700;margin-bottom:12px">
            THE FRAMEWORK — HOW TO APPLY THIS EACH YEAR
          </div>
          <div style="font-size:12px;line-height:1.8;color:#e8e8f0">
            <strong style="color:#c8ff00">Step 1</strong> — Find the position with the most R1–R2 value clustered below its expected ADP.
            In 2022 that was WR. In 2024 it was RB. In 2025 it was TE. The market creates a different
            "best play" each year.<br><br>
            <strong style="color:#c8ff00">Step 2</strong> — Identify the QB available in R7–R8 with a track record.
            Prescott, Goff, and Cousins appear repeatedly as undervalued.
            <strong style="color:#ff4d6d">Avoid R6 QBs</strong> — Watson, Murray, Nix, Purdy all busted there.<br><br>
            <strong style="color:#c8ff00">Step 3</strong> — Recognize the year's bust archetype.
            2021: injury-prone WRs. 2022: SF skill players. 2023: mobile QBs early. 2024: WR R2–R3. 2025: anything R3–R6.<br><br>
            <strong style="color:#c8ff00">The only universal rules:</strong>
            RB R1–R3 is <strong style="color:#00ff88">always positive VORP (5/5 years)</strong>.
            WR R8–R10 is <strong style="color:#ff4d6d">always negative VORP (5/5 years)</strong>.
            RB R9–R11 is nearly always negative. These don't change year to year.
          </div>
        </div>
        """, unsafe_allow_html=True)

        # Explorer: position × round drill-down
        st.markdown("<br>", unsafe_allow_html=True)
        st.markdown("##### Player Explorer — Filter by Position & Round")
        col1, col2, col3 = st.columns(3)
        with col1:
            sel_pos = st.selectbox("Position", ["QB","RB","WR","TE"], key="exp_pos")
        with col2:
            sel_rnd = st.selectbox("Round", list(range(1, 14)), key="exp_rnd")
        with col3:
            sel_yr  = st.multiselect("Season(s)", [2021,2022,2023,2024,2025],
                                      default=[2021,2022,2023,2024,2025], key="exp_yr")

        if not full_df.empty:
            filt = full_df[
                (full_df["position"] == sel_pos) &
                (full_df["adp_round"] == sel_rnd) &
                (full_df["season"].isin(sel_yr))
            ].sort_values("vorp_pg", ascending=False)

            if not filt.empty:
                display_cols = ["season","player_name","adp","fpts_pg","vorp_pg","outcome"]
                st.dataframe(
                    filt[display_cols].rename(columns={
                        "season":"Year","player_name":"Player","adp":"ADP",
                        "fpts_pg":"Pts/gm","vorp_pg":"VORP/gm","outcome":"Outcome"
                    }).style.background_gradient(subset=["VORP/gm"], cmap="RdYlGn"),
                    use_container_width=True,
                )
                avg_v = filt["vorp_pg"].mean()
                hit_r = (filt["vorp_pg"] > 1.0).mean() * 100
                bust_r= (filt["vorp_pg"] < 0).mean() * 100
                st.caption(f"n={len(filt)} · Avg VORP/gm: {avg_v:+.2f} · Hit rate: {hit_r:.0f}% · Bust rate: {bust_r:.0f}%")
            else:
                st.info("No data for this combination.")
